export const defaultAttributes = ['for', 'des', 'con', 'int', 'sab', 'car']
export const defaultPower = ['acuidade com arma']
export const defaultSizes = [
	'minúsculo',
	'pequeno',
	'médio',
	'grande',
	'enorme',
	'colossal',
]
export const defaultSkills = [
	'acrobacia',
	'adestramento',
	'atletismo',
	'atuação',
	'cavalgar',
	'conhecimento',
	'cura',
	'diplomacia',
	'enganação',
	'fortitude',
	'furtividade',
	'guerra',
	'iniciativa',
	'intimidação',
	'intuição',
	'investigação',
	'jogatina',
	'ladinagem',
	'luta',
	'misticismo',
	'nobreza',
	'percepção',
	'pilotagem',
	'pontaria',
	'reflexos',
	'religião',
	'sobrevivência',
	'vontade',
	'ofício',
]
